### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by jfranciscos4** [vrcca/flyway-vagrant-puppet-postgres-example#2]
Vagrant failed to initialize at a very early stage:

There is a syntax error in the following Vagrantfile. The syntax error
message is reproduced below for convenience:

/home/jfsi/workspacePHP/github/flyway-vagrant-puppet-postgres-example/Vagrantfile:6: invalid multibyte char (US-ASCII)
/home/jfsi/workspacePHP/github/flyway-vagrant-puppet-postgres-example/Vagrantfile:6: invalid multibyte char (US-ASCII)
/home/jfsi/workspacePHP/github/flyway-vagrant-puppet-postgres-example/Vagrantfile:6: syntax error, unexpected $end, expecting keyword_end
  raise "É necessário instalar o plugi...
           ^

**Comment by jfranciscos4** [comment]
Bicho, resolve ai!

**Comment by vrcca** [comment]
@jfranciscos4 Você chegou a resolver este problema?

**Comment by jfranciscos4** [comment]
Não

**Comment by vrcca** [comment]
Corrigido no PR1.
